export * from './blue';
export * from './cyan';
export * from './gray';
export * from './green';
export * from './orange';
export * from './pink';
export * from './purple';
export * from './red';
export * from './yellow';
